### ISSUE TITLE
Host website on github

### ISSUE THREAD

**Issue by sxu2583** [swindleNswoon/bronxCodeCamp#3]
You can open a gh-pages branch

**Comment by kemcrimmins** [comment]
How does that work? What does it do? (Sorry, learning github/git on the fly...)

**Comment by sxu2583** [comment]
What that does is it basically hosts the code on this repo onto a github address. So in the code section you'll see something that says branch.  I'd explain it but heres a better set of steps 

https://pages.github.com/

**Comment by swindleNswoon** [comment]
Done. Link included in README. Thank you sxu2583
